Adding "well, actually" back as an example
w3c/PWETF pull request #300
Opened 2023-06-20 18:46 UTC by wareid

By popular request, everyone's favourite example of patronizing language.

2023-06-20 18:50 UTC, TzviyaSiegman approved these changes

2023-06-21 08:49 UTC, nigelmegitt requested changes
Please don't do this. So many arguments in the past, that I'd summarise as: "this is a highly contentious example that works well for some groups and absolutely not at all for other groups." In other words, it's a poor choice of example to use in a global-facing document.

2023-06-21 15:31 UTC, cwilso commented
I will also add, as someone who probably used to say "well, actually" with embarrassing frequency - it is better to have this example, and have users of the phrase question it whenever they say it.  I agree, @nigelmegitt , that there are contexts that it is not a problematic phrase - but there are far more occurrences where it likely *IS* causing unintended offense.  This is not a blanket prohibition of using the phrase in any context, but it is more problematic than it might seem.  

(*ObApology to everyone I might have unintentionally offended using this phrase in the past here*)

2023-06-21 15:51 UTC, nigelmegitt commented
I am sure I fall into the same category @cwilso ! Nevertheless, while I understand your point, I disagree on the outcome: it does look like a blanket prohibition.

@wareid I am sure that _you_ understand the different tones and uses, but for those who don't, i.e. the target audience, I would contend that it is not even useful as an educational tool, for precisely the reason that the usage context is missing. 

> I think the feedback needs to win here

Well, W3C works on consensus, and I am clearly blocking consensus on adopting this change in this document.

I do think that some longer worked examples in a separate guidance document, including this phrase, could be extremely helpful though.

2023-06-21 17:49 UTC, wareid commented
I can't make any promises regarding an accompanying guidance document, nor do I think one would remotely be helpful. This document is already quite extensive and I don't think we gain anything by adding even more content. What would the guidance document even say? We can't coach people through every potential interaction. 

We added this back because many people wanted it back, particularly people who had had the phrase used against them. This document is always going to be more attuned to the needs of people on the receiving end of bad behaviour as a resource to guide when something feels wrong. 

Nigel, we really need a more substantive explanation for the opposition outside of it being context dependent, because half of the CoC is context dependent, that is the nature of documents like these. It would be fantastic if we could write this like a technical specification, that is unfortunately not possible.

2023-06-21 18:09 UTC, tantek approved these changes
Great commonly seen example to add explicitly, and especially in the context of a global community that uses English as a default, with many non-native English speakers that may not have familiarity with the nuances or historical abuse of such colloquialisms. 

I see including this example as an act of kindness for non-native English speakers, who may otherwise hear such expressions from native English speakers and accidentally pick-up and re-use them without knowing their potential harms (or context sensitivity).

I will admit I have seen "Well, actually" used in sarcasm, satire, and irony, however even those uses don't typically contribute to a "positive environment" so I think it's still ok to include this explicitly, and instead rely on the goodwill of anyone attempting to use the phrase in those ways to accept pushback and kindly handle any conflict management.

2023-06-21 18:20 UTC, dbooth-boston commented
Wait, this PR contains the wrong language.  The language that was [agreed on yesterday's call](https://www.w3.org/2023/06/20-pwe-minutes.html) was this, which provides considerably more informative explanation:

> Be aware that, regardless of the speaker's intentions, some phrases or constructions lead people to expect a patronizing statement to follow, and avoid such phrases. For example, beginning an interjection with "Well, actually..." can set this expectation and be taken as a sign of disrespect.

2023-06-21 18:50 UTC, TzviyaSiegman commented
We try to base our work on research. @elenalape shared this CoC with me https://github.com/compsoc-edinburgh/code-of-conduct. Perhaps the definition of well actually here would help explain why we would like to include this.
"Well-actuallys. That is the pedantic corrections that don’t make a difference to the conversation that’s happening."

2023-06-22 03:47 UTC, dbooth-boston commented
> "Well-actuallys. That is the pedantic corrections that don’t make a difference to the conversation that’s happening."

Wow, that definition sounds very different than the way our CoC was describing the term.  That description sounds much more like disruption of discussion than being patronizing.

But regardless, @nigelmegitt , does the verbiage that was [agreed by the group](https://www.w3.org/2023/06/20-pwe-minutes.html) and should have been in this PR -- i.e.,  _not_ the current content of this PR -- address your concerns enough for you to live with it?  The agreed verbiage was this:

> Be aware that, regardless of the speaker's intentions, some phrases or constructions lead people to expect a patronizing statement to follow, and avoid such phrases. For example, beginning an interjection with "Well, actually..." can set this expectation and be taken as a sign of disrespect.

2023-06-22 09:50 UTC, nigelmegitt commented
The wording in https://github.com/w3c/PWETF/pull/300#issuecomment-1601360302 is much less problematic and I would be able to accept it.

2023-06-23 15:34 UTC, wareid commented
@nigelmegitt @dbooth-boston I've edited this to add that language (some further editing for fit and clarity). Does this satisfy your concerns?

2023-06-23 16:05 UTC, dbooth-boston commented
Yes, that looks fine to me.

2023-06-26 09:17 UTC, nigelmegitt approved these changes

2023-06-26 20:10 UTC, TzviyaSiegman approved these changes

2023-06-26 20:35 UTC, merged