Adding Changelog and Acknowledgements
w3c/PWETF pull request #303
Opened 2023-07-11 16:28 UTC by wareid

Adding changelog and acknowledgements sections.

If I have forgotten anyone, please let me know!

2023-07-12 17:56 UTC, TzviyaSiegman requested changes

2023-07-12 17:56 UTC, TzviyaSiegman commented on index.html
> +          16-May-2023: Added editorial recommendations from three issues (<a href="https://github.com/w3c/PWETF/issues/260">#260</a>, <a href="https://github.com/w3c/PWETF/issues/261">#261</a>, and <
behavior (american spelling)

2023-07-12 17:56 UTC, TzviyaSiegman commented on index.html
> +          7-Jun-2022: Added "deliberate misinformation" as an unacceptable behaviour. See <a href="https://github.com/w3c/PWETF/pull/201">PR #201</a>.
behavior (US spelling)

2023-07-12 20:33 UTC, TzviyaSiegman commented on index.html
> +        <li>David Booth (W3C Invited Expert)</li>
Judy Brewer

2023-07-12 20:33 UTC, TzviyaSiegman commented on index.html
> +        <li>David Booth (W3C Invited Expert)</li>
Jory Burson

2023-07-12 20:47 UTC, TzviyaSiegman commented on index.html
> +        <li>JaEun Jemma Ku (University of Illinois)</li>
Vlad Levantovsky

2023-07-12 20:47 UTC, TzviyaSiegman commented on index.html
> +        <li>David Booth (W3C Invited Expert)</li>
first thanks is to Ann Bassetti

2023-07-12 20:48 UTC, TzviyaSiegman commented on index.html
> +        <li>Nigel Megitt (BBC)</li>
Coralie Mercier, W3C

2023-07-12 20:48 UTC, TzviyaSiegman commented on index.html
> +        <li>David Booth (W3C Invited Expert)</li>
Dan Appelquist

2023-07-12 20:49 UTC, TzviyaSiegman commented on index.html
> +        <li>Jennifer Stricßkland (MITRE Corporation)</li>
extra character in Strickland

2023-07-12 20:52 UTC, TzviyaSiegman requested changes

2023-07-12 20:52 UTC, TzviyaSiegman commented on index.html
> +        <li>Ralph Swick (W3C)</li>
Swick is out of alpha, Add Wendy Seltzer

2023-07-13 15:10 UTC, wareid commented
Names added and fixed the Canadian-isms.

2023-07-13 19:36 UTC, merged