Give ids to all entries in the behavior lists
w3c/PWETF pull request #366
Opened 2024-01-30 22:59 UTC by frivoal

This enables linking directly to a specific entry, to make it easier to reference individual entries

This does not change any of the wording in any part of the document ([class 1 change](https://www.w3.org/Consortium/Process/#class-1), in Process terminology)

2024-01-31 01:19 UTC, dbooth-boston requested changes
Thanks for doing this!  I made several suggestions, mostly intended to help the anchors better survive potential future edits and additions.

2024-01-31 01:19 UTC, dbooth-boston commented on index.html
> +          <li id=criticism>Critizing oppressive behavior or assumptions, such as those that are <a>racist</a>, <a>sexist</a>, or <a>cissexist</a>.
Suggest: s/id=criticism/id=criticizing-oppression/

2024-01-31 01:19 UTC, dbooth-boston commented on index.html
> +          <li id=promote>Be <a>inclusive</a> and promote <a>diversity</a>. Seek diverse
Suggest: s/id=promote/id=promote-diversity/

2024-01-31 01:19 UTC, dbooth-boston commented on index.html
> +          <li id=dominant>Be aware of how much time is taken up by dominant members of the
Suggest: s/id=dominant/id=dominating/

2024-01-31 01:19 UTC, dbooth-boston commented on index.html
> +          <li id=biases>Work to eliminate your own biases, <a>prejudices</a>, and discriminatory
Suggest: s/id=biases/id=eliminate-bias/

2024-01-31 01:19 UTC, dbooth-boston commented on index.html
> +          <li id=accomodate>Accommodate participants' needs for physical distancing and other accommodations or precautions due to health concerns such as immune deficiency, allergies, or chemical se
Suggest: s/id=accomodate/id=accommodate/

2024-01-31 01:19 UTC, dbooth-boston commented on index.html
> +          <li id=unwelcome>Unwelcome comments regarding a person’s lifestyle choices and
Suggest: s/id=unwelcome/id=lifestyle-comments/

2024-01-31 01:19 UTC, dbooth-boston commented on index.html
> +          <li id=attacks>Personal attacks.
Suggest: s/id=attacks/id=personal-attacks/

2024-01-31 01:19 UTC, dbooth-boston commented on index.html
> +          <li id=outing>Deliberate outing of any aspect of a person’s <a>gender
Suggest: s/id=outing/id-gender-outing/

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=dominant>Be aware of how much time is taken up by dominant members of the
```suggestion
          <li id=dominating>Be aware of how much time is taken up by dominant members of the
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=promote>Be <a>inclusive</a> and promote <a>diversity</a>. Seek diverse
```suggestion
          <li id=promote-diversity>Be <a>inclusive</a> and promote <a>diversity</a>. Seek diverse
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=biases>Work to eliminate your own biases, <a>prejudices</a>, and discriminatory
```suggestion
          <li id=eliminate-bias>Work to eliminate your own biases, <a>prejudices</a>, and discriminatory
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=accomodate>Accommodate participants' needs for physical distancing and other accommodations or precautions due to health concerns such as immune deficiency, allergies, or chemical se
```suggestion
          <li id=accommodate>Accommodate participants' needs for physical distancing and other accommodations or precautions due to health concerns such as immune deficiency, allergies, or chemical sensitivity.</li>
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=unwelcome>Unwelcome comments regarding a person’s lifestyle choices and
```suggestion
          <li id=lifestyle-comments>Unwelcome comments regarding a person’s lifestyle choices and
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=gratuitous>Gratuitous or off-topic sexual images or behavior in spaces where
```suggestion
          <li id=sexual-images>Gratuitous or off-topic sexual images or behavior in spaces where
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=contact>Physical contact and simulated physical contact (e.g., textual
```suggestion
          <li id=non-consensual-contact>Physical contact and simulated physical contact (e.g., textual
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=violence>Incitement of violence towards any individual, including
```suggestion
          <li id=incitement>Incitement of violence towards any individual, including
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=attacks>Personal attacks.
```suggestion
          <li id=personal-attacks>Personal attacks.
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=sexual><a>Unwelcome sexual attention</a>.
```suggestion
          <li id=sexual-attention><a>Unwelcome sexual attention</a>.
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=inappropriate>Patterns of inappropriate social contact, such as
```suggestion
          <li id=inappropriate-contact>Patterns of inappropriate social contact, such as
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=outing>Deliberate outing of any aspect of a person’s <a>gender
```suggestion
          <li id=gender-outing>Deliberate outing of any aspect of a person’s <a>gender
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=publication>Publication of non-harassing private communication without
```suggestion
          <li id=publishing-private-comm>Publication of non-harassing private communication without
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +              <li id=grandmother>Assuming that particular groups of people are technically unskilled due to their characteristics (e.g., “So easy your grandmother could do it”, which implies an older
```suggestion
              <li id=assuming-unskilled>Assuming that particular groups of people are technically unskilled due to their characteristics (e.g., “So easy your grandmother could do it”, which implies an older woman might not be technically competent).
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +              <li id=unnecessary>Interrupting or repeatedly commenting in conversations with unneccessary clarifications or comments on audience behaviour (e.g., "I don't think you understood my prev
```suggestion
              <li id=unnecessary-comments>Interrupting or repeatedly commenting in conversations with unneccessary clarifications or comments on audience behaviour (e.g., "I don't think you understood my previous comment...", grammar or language corrections that were not invited).</li>
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +              <li id=actually>Regardless of the speaker's intentions, some phrases or constructions lead people to expect a patronizing statement to follow. For example, beginning an interjection wit
```suggestion
              <li id=well-actually>Regardless of the speaker's intentions, some phrases or constructions lead people to expect a patronizing statement to follow. For example, beginning an interjection with a phrase like "Well, actually..." can set this expectation and be taken as a sign of disrespect.</li>
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +              <li id=surprise>Feigning surprise at someone’s lack of knowledge or awareness
```suggestion
              <li id=feigning-surprise>Feigning surprise at someone’s lack of knowledge or awareness
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +              <li id=charged>The use of racially charged language to describe an
```suggestion
              <li id=racist-language>The use of racially charged language to describe an
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +              <li id=demeans>Referring to an individual in a way that <a>demeans</a> or
```suggestion
              <li id=demeaning>Referring to an individual in a way that <a>demeans</a> or
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=boundaries>Reasonable communication of boundaries, such as “leave me alone,”
```suggestion
          <li id=setting-boundaries>Reasonable communication of boundaries, such as “leave me alone,”
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=congenial>Communication in a tone you don’t find congenial.
```suggestion
          <li id=non-congenial-tone>Communication in a tone you don’t find congenial.
```

2024-01-31 02:57 UTC, frivoal commented on index.html
> +          <li id=criticism>Critizing oppressive behavior or assumptions, such as those that are <a>racist</a>, <a>sexist</a>, or <a>cissexist</a>.
```suggestion
          <li id=criticizing-oppression>Critizing oppressive behavior or assumptions, such as those that are <a>racist</a>, <a>sexist</a>, or <a>cissexist</a>.
```

2024-01-31 03:02 UTC, frivoal commented
Thanks @dbooth-boston, I accepted all the suggestions. I am unsure how much it matters to have good phraising for the ids, but to the extent it does, your suggestions seemed like improvements.

2024-01-31 14:16 UTC, wareid approved these changes

2024-02-07 21:08 UTC, merged

2024-02-08 17:37 UTC, wareid commented
> It's very opaque to viewers of the page that these IDs exist. Is there anything we can do (maybe in CSS?) to expose the links with fragment IDs? I'm thinking about the hover-over chain link icon pattern, though I'm unsure about the accessibility of _only_ offering the link that way.

I don't disagree @nigelmegitt, I wonder if this might be a respec recommendation though? I could probably work something into the document but it would be a hack and might be better to have built into respec.

2024-02-08 20:22 UTC, frivoal commented
Bikeshed makes this kind of thing a lot more easily discoverable, by adding a hoverable gray "§" in the margin of any such links, but respec currently doesn't. It'd be great if it did.