The code of conduct is expected to be hosted under /policies/
w3c/PWETF pull request #367
Opened 2024-02-01 14:58 UTC by deniak

We expect to host that document under /policies/. That PR updates the different links to have:
* /policies/code-of-conduct/ serving the latest published dated version
* /policies/code-of-conduct/drafts/ serving the editors draft which is a proxy to https://w3c.github.io/PWETF/

2024-02-01 15:08 UTC, TzviyaSiegman commented
What about /policies/CoC (at least as a redirect?) And, I assume the old https://www.w3.org/Consortium/cepc/ will at least redirect to this.

2024-02-01 16:07 UTC, deniak commented
> What about /policies/CoC (at least as a redirect?) 

We did think about that one but "CoC" may not sound good for some people...

> And, I assume the old https://www.w3.org/Consortium/cepc/ will at least redirect to this.

Yes, the idea is to redirect https://www.w3.org/Consortium/cepc/ to https://www.w3.org/policies/code-of-conduct/ once it's ready.

2024-02-01 17:00 UTC, vivienlacourba commented
> > What about /policies/CoC (at least as a redirect?)
> 
> We did think about that one but "CoC" may not sound good for some people...

And we are also following the new website URI naming scheme where we use lower case letters.

2024-02-01 17:11 UTC, wareid approved these changes

2024-02-01 17:11 UTC, vivienlacourba requested changes

2024-02-01 17:11 UTC, vivienlacourba commented on index.html
> +	          href: "http://www.w3.org/policies/code-of-conduct/" }
Use https link

```suggestion
	          href: "https://www.w3.org/policies/code-of-conduct/" }
```

2024-02-01 17:20 UTC, vivienlacourba approved these changes

2024-02-02 01:47 UTC, xueyuanjia approved these changes

2024-02-02 02:34 UTC, merged